//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTodoList
    {
        public int categorytodolistid { get; set; }
        public int todolistid { get; set; }
        public int categoryid { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual TodoList TodoList { get; set; }
    }
}
