//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoItem
    {
        public int todoitemid { get; set; }
        public int todolistid { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public byte complete { get; set; }
    
        public virtual TodoList TodoList { get; set; }
    }
}
